# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06b8e8b6a6824a77be0e493febddcb5b61d7f62836b68c9349fd2ed53e5aa52b52432aaf2eea71a09d2f415b47a03ee3e19b99132a384525c344ef938136df5e

test:
  secret_key_base: d50d50bb4c5b427f025557077142261336c85d420fa1f931a079493139f47df5bec1a34fb8d95eba4f29f932184b89e8226ecaa24b7a82be57869f74e2a9ec40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
